package com.example.telecinema.util

import kotlinx.serialization.json.Json

object Lang {
    private val ar = mapOf(
        "appName" to "تلي سينما",
        "movies" to "الأفلام",
        "channels" to "القنوات",
        "favorites" to "المفضلة",
        "history" to "السجل",
        "downloads" to "التحميلات",
        "settings" to "الإعدادات",
        "sites" to "المواقع",
        "discover" to "استكشف",
        "achievements" to "الإنجازات",
        "addChannel" to "إضافة قناة",
        "addChannelHint" to "اسم المستخدم أو الرابط (مثال: @cinema)",
        "channelAdded" to "تمت إضافة القناة بنجاح",
        "channelNotFound" to "لم يتم العثور على القناة أو لا توجد فيديوهات",
        "deleteChannel" to "حذف القناة",
        "deleteConfirm" to "هل تريد حذف هذه القناة والأفلام التابعة لها؟",
        "cancel" to "إلغاء",
        "delete" to "حذف",
        "play" to "تشغيل",
        "continueWatching" to "متابعة المشاهدة",
        "popular" to "الأكثر مشاهدة",
        "latest" to "أحدث الإضافات",
        "search" to "بحث عن فيلم...",
        "noMovies" to "لا توجد أفلام",
        "noChannels" to "لا توجد قنوات بعد",
        "noChannelsHint" to "أضف قنوات تليجرام لمشاهدة الأفلام",
        "noFavorites" to "لا توجد أفلام في المفضلة",
        "noHistory" to "سجل المشاهدة فارغ",
        "noDownloads" to "لا توجد تحميلات",
        "resumePrompt" to "هل تريد المتابعة من حيث توقفت؟",
        "startFromBeginning" to "من البداية",
        "resume" to "متابعة",
        "quality" to "الجودة",
        "selectQuality" to "اختر الجودة",
        "comments" to "التعليقات",
        "addComment" to "أضف تعليقاً...",
        "send" to "إرسال",
        "rate" to "تقييم",
        "download" to "تحميل",
        "downloadStarted" to "بدأ التحميل",
        "downloadCompleted" to "اكتمل التحميل",
        "shareCard" to "مشاركة البطاقة",
        "wheelOfFortune" to "عجلة الحظ 🎡",
        "spin" to "تدوير",
        "shotGame" to "لقطة اليوم 🎬",
        "guessMovie" to "خمّن الفيلم من اللقطة",
        "correct" to "إجابة صحيحة! 🎉",
        "wrong" to "إجابة خاطئة! حاول مجدداً",
        "nextRound" to "الجولة التالية",
        "limitedTime" to "وقتي محدود ⏱️",
        "pickTime" to "اختر المدة المتاحة لديك",
        "all" to "الكل",
        "archive" to "الأرشيف",
        "plex" to "Plex",
        "roku" to "Roku",
        "crackle" to "Crackle",
        "language" to "اللغة",
        "arabic" to "العربية",
        "english" to "English",
        "appearance" to "المظهر واللون",
        "viewMode" to "طريقة العرض",
        "grid" to "شبكة",
        "list" to "قائمة",
        "hideWatched" to "إخفاء المشاهدة",
        "incognito" to "الوضع الخفي",
        "incognitoHint" to "عدم حفظ الأفلام في سجل المشاهدة",
        "kidsMode" to "وضع الأطفال",
        "kidsModeHint" to "إخفاء الأفلام العنيفة أو غير المناسبة",
        "vault" to "القبو السري 📦",
        "lockVault" to "قفل القبو",
        "unlockVault" to "فتح القبو",
        "setPin" to "تعيين رمز PIN",
        "enterPin" to "أدخل رمز PIN",
        "stats" to "الإحصائيات",
        "hoursWatched" to "ساعات مشاهدة",
        "moviesWatched" to "فيلم تم مشاهدته",
        "streak" to "سلسلة المشاهدة",
        "days" to "أيام",
        "backup" to "النسخ الاحتياطي",
        "exportData" to "تصدير البيانات",
        "importData" to "استيراد البيانات",
        "exportSuccess" to "تم التصدير بنجاح",
        "importSuccess" to "تم الاستيراد بنجاح",
        "filter" to "تصفية",
        "sort" to "ترتيب",
        "sortNewest" to "الأحدث",
        "sortOldest" to "الأقدم",
        "sortTitle" to "أبجدياً",
        "sortYear" to "سنة الإنتاج",
        "sortDuration" to "المدة",
        "refresh" to "تحديث",
        "failedPlay" to "تعذر تشغيل الفيديو"
    )

    private val en = mapOf(
        "appName" to "Tele Cinema",
        "movies" to "Movies",
        "channels" to "Channels",
        "favorites" to "Favorites",
        "history" to "History",
        "downloads" to "Downloads",
        "settings" to "Settings",
        "sites" to "Sources",
        "discover" to "Discover",
        "achievements" to "Achievements",
        "addChannel" to "Add Channel",
        "addChannelHint" to "Username or Link (e.g. @cinema)",
        "channelAdded" to "Channel added successfully",
        "channelNotFound" to "Channel not found or has no videos",
        "deleteChannel" to "Delete Channel",
        "deleteConfirm" to "Do you want to delete this channel and its movies?",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "play" to "Play",
        "continueWatching" to "Continue Watching",
        "popular" to "Most Popular",
        "latest" to "Recently Added",
        "search" to "Search movies...",
        "noMovies" to "No movies found",
        "noChannels" to "No channels added yet",
        "noChannelsHint" to "Add Telegram channels to stream movies",
        "noFavorites" to "No favorites yet",
        "noHistory" to "Watch history is empty",
        "noDownloads" to "No downloads",
        "resumePrompt" to "Resume where you left off?",
        "startFromBeginning" to "Start Over",
        "resume" to "Resume",
        "quality" to "Quality",
        "selectQuality" to "Select Quality",
        "comments" to "Comments",
        "addComment" to "Add a comment...",
        "send" to "Send",
        "rate" to "Rate",
        "download" to "Download",
        "downloadStarted" to "Download started",
        "downloadCompleted" to "Download completed",
        "shareCard" to "Share Card",
        "wheelOfFortune" to "Wheel of Fortune 🎡",
        "spin" to "Spin",
        "shotGame" to "Movie Shot Quiz 🎬",
        "guessMovie" to "Guess the movie from the scene",
        "correct" to "Correct Answer! 🎉",
        "wrong" to "Wrong answer! Try again",
        "nextRound" to "Next Round",
        "limitedTime" to "Time Budget ⏱️",
        "pickTime" to "Choose how much time you have",
        "all" to "All",
        "archive" to "Archive",
        "plex" to "Plex",
        "roku" to "Roku",
        "crackle" to "Crackle",
        "language" to "Language",
        "arabic" to "العربية",
        "english" to "English",
        "appearance" to "Appearance",
        "viewMode" to "View Mode",
        "grid" to "Grid",
        "list" to "List",
        "hideWatched" to "Hide Watched",
        "incognito" to "Incognito Mode",
        "incognitoHint" to "Do not save watched movies in history",
        "kidsMode" to "Kids Mode",
        "kidsModeHint" to "Hide violent or mature content",
        "vault" to "Secret Vault 📦",
        "lockVault" to "Lock Vault",
        "unlockVault" to "Unlock Vault",
        "setPin" to "Set PIN Code",
        "enterPin" to "Enter PIN Code",
        "stats" to "Statistics",
        "hoursWatched" to "Hours Watched",
        "moviesWatched" to "Movies Watched",
        "streak" to "Watch Streak",
        "days" to "Days",
        "backup" to "Backup",
        "exportData" to "Export Data",
        "importData" to "Import Data",
        "exportSuccess" to "Exported successfully",
        "importSuccess" to "Imported successfully",
        "filter" to "Filter",
        "sort" to "Sort",
        "sortNewest" to "Newest",
        "sortOldest" to "Oldest",
        "sortTitle" to "Alphabetical",
        "sortYear" to "Release Year",
        "sortDuration" to "Duration",
        "refresh" to "Refresh",
        "failedPlay" to "Could not play video"
    )

    fun t(key: String, locale: String = "ar"): String {
        val map = if (locale.lowercase() == "en") en else ar
        return map[key] ?: key
    }

    /**
     * Arabic search normalization
     */
    fun normalizeArabic(text: String): String {
        return text.lowercase()
            .replace(Regex("[أإآا]"), "ا")
            .replace("ة", "ه")
            .replace("ى", "ي")
            .replace("ؤ", "و")
            .replace("ئ", "ي")
            .replace(Regex("[\u064B-\u065F]"), "") // Remove diacritics / tashkeel
            .trim()
    }
}

val AppJson = Json {
    ignoreUnknownKeys = true
    isLenient = true
    encodeDefaults = true
}
